[package]
name = "efficient_route_planning"
version = "0.1.0"
authors = ["Simon Gibbons <simongibbons@gmail.com>"]

[dependencies]
geo = "0.7.1"
itertools = "0.7.3"
serde_derive = "1.0"
serde = "1.0"
serde-xml-rs = "0.2.1"
